### ISSUE TITLE
No module named 'OpenAI" - Cannot install extension

### ISSUE THREAD

**Issue by revolvedai** [if-ai/IF_prompt_MKR#11]
Got this error trying to install:
*** Error loading script: if_prompt_mkr.py
    Traceback (most recent call last):
      File "E:\SD\stable-diffusion-webui\modules\scripts.py", line 469, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\SD\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\SD\stable-diffusion-webui\extensions\IF_prompt_MKR\scripts\if_prompt_mkr.py", line 19, in <module>
        from openai import OpenAI
    ModuleNotFoundError: No module named 'openai'

I go the installation locally and while trying to install on RunDiffusion.

**Comment by if-ai** [comment]
it just needs to pip install openai on A1111 environment. I added a new file that should do it automatically when you start A1111 SDnext or Forge
